# Generated by Django 2.2.6 on 2019-11-11 01:28

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmtproject', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='profilepicpath',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='booksissued',
            name='issue_date',
            field=models.DateField(default=datetime.date(2019, 11, 11)),
        ),
    ]
