# Generated by Django 2.2.6 on 2019-11-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmtproject', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('price', models.FloatField(null=True)),
                ('pages', models.IntegerField()),
                ('noofcopies', models.IntegerField()),
                ('published_date', models.DateField()),
            ],
        ),
    ]
