# Generated by Django 2.2.6 on 2019-11-04 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmtproject', '0002_book'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationHouse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('ratings', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='book',
            name='publication',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='libmgmtproject.PublicationHouse'),
            preserve_default=False,
        ),
    ]
