# Generated by Django 2.2.6 on 2019-11-05 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('libmgmtproject', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='students',
            field=models.ManyToManyField(to='libmgmtproject.Student'),
        ),
    ]
